const fs = require('node:fs');
const config = require('../config/my_config');
const emojis = require('./emoji.js')();

const getPokemonFile = function (name, shiny, gender, form, fileType) {
    let nameInFile = name.toLowerCase();

    /**
     * Replace special characters in pokemon name
     */
    nameInFile = name.replace(/'/g,"_");
    nameInFile = name.replace(/ /g,"_");
    nameInFile = name.replace(/é/g,"e");
    nameInFile = name.replace(/./g,"");
    nameInFile = name.replace(/:/g,"");
    
    if (form != null) {
        form = form.toLowerCase();
        /**
         * Oricorio has a form name with an apostrophe in it.
         */
        form = form.replace(/'/g,"-");
        /**
         * Multiple Pokemon have form names with spaces in it.
         */
        form = form.replace(/ /g,"-");
        /**
         * Vivillon has a form name with an acute e in it.
         */
        form = form.replace(/é/g,"e");
        nameInFile += "-" + form;
    } else { /* =======================================================================
        if (gender === "female") {
            if (hasGenderDifference(this) === true) {
                nameInFile += "-f";
            }
        } */
    }

    if (shiny == true) {
        nameInFile += "-s";
    }

    let finalFileName;

    if (fileType == "image") {
        finalFileName = config.pokemonImageLink + nameInFile + ".png?raw=true";
    } else if (fileType == "json") {
        finalFileName = "./data/pokemon/" + nameInFile + ".json";
    }

    return finalFileName;
};

module.exports = function() {
    this.getAllPokemon = function(alphabetical) {
        fs.readFile('./data/pokedex.json', function(err, data) { 

            if (err) throw err; 

            let pokemon = JSON.parse(data);
            console.log(pokemon.pokedex);
            if (alphabetical == true) {
                return pokemon.pokedex.sort();
            } else {
                return pokemon.pokedex;
            }
        }); 
    }

    this.getPokeImage = function(name, shiny, gender, form) {
        return getPokemonFile(name, shiny, gender, form, "image");

    }

    this.getOnePokemon = function(name, gender, form) {
        let filePath = getPokemonFile(name, null, gender, form, "json");
        return new Promise(function(resolve) {
            fs.readFile(filePath, function(err, data) { 
                if (err) throw err; 
                const pokemon = JSON.parse(data);
                resolve(pokemon);
            });
        });
    }

    this.dexNumberToString = function(name) {
        let num = String(name.national_id);
        let zeroes = 4 - num.length;
        while (zeroes > 0) {
            num = "0" + num;
            zeroes--;
        }
        return num;
    }

    this.getTypeString = function(types) {
        let i = 0;
        let typeString = "";
        while (i < types.length) {
            typeString += (typeEmoji[types[i].toLowerCase()]);
            i++;
        }
        return typeString;
    }

    this.getMiscString = function(pokemon) {
        let miscString = "";
        miscString += ("Base XP Yield: " + pokemon.base_exp_yield + "\n");
        miscString += ("Leveling Rate: " + pokemon.leveling_rate + "\n");
        miscString += ("Base Friendship: " + pokemon.base_friendship + "\n");
        
        if (pokemon.gender_ratios == null) {
            miscString += ("Gender %: ♂️ 0 / ♀️ 0");
        } else if (!pokemon.gender_ratios.hasOwnProperty("male")) {
            miscString += ("Gender %: ♂️ 0 / ♀️ 100\n");
        } else if (!pokemon.gender_ratios.hasOwnProperty("female")) {
            miscString += ("Gender %: ♂️ 100 / ♀️ 0\n");
        } else {
            miscString += ("Gender %: ♂️ " + pokemon.gender_ratios.male + " ♀️ " + pokemon.gender_ratios.female + "\n");
        }

        miscString += "Egg Groups: ";
        pokemon.egg_groups.forEach((group) => {
            miscString += (group + ", ");
        });

        miscString = miscString.substring(0, miscString.length - 2);

        miscString += "\nHatch Time: WIP";

        return miscString;
    }

    this.getAbilityString = function(abilities) {
        let i = 0;
        let abilityString = "";
        while (i < abilities.length) {
            if (abilities[i].hasOwnProperty("hidden")) {
                abilityString += ("_" + abilities[i].name + "_")
            } else {
                abilityString += (abilities[i].name + "\n");
            }
            i++;
        }
        return abilityString;
    }

    this.getBaseStatsString = function(stats) {
        let statsString = "";
        statsString += ("HP: " + stats.hp + "\n");
        statsString += ("Attack: " + stats.atk + "\n");
        statsString += ("Defense: " + stats.def + "\n");
        statsString += ("SpAtk: " + stats.sp_atk + "\n");
        statsString += ("SpDef: " + stats.sp_def + "\n");
        statsString += ("Speed: " + stats.speed);
        return statsString;
    }

    this.getEVYieldsString = function(evs) {
        let evString = "";
        evString += ("HP: " + evs.hp + "\n");
        evString += ("Attack: " + evs.atk + "\n");
        evString += ("Defense: " + evs.def + "\n");
        evString += ("SpAtk: " + evs.sp_atk + "\n");
        evString += ("SpDef: " + evs.sp_def + "\n");
        evString += ("Speed: " + evs.speed);
        return evString;
    }

    this.getWildHeldItemsString = function(pokemon) {
        let itemsString = "";
        if (pokemon.hasOwnProperty("items")) {
            pokemon.items.forEach((item) => {
                itemsString += (item.name + " (" + item.chance + "%)\n");
            });
        } else {
            itemsString = "None";
        }
        return itemsString;
    }

    this.getTypeColor = function(type) {
        if (type === "Normal") {
            return 0xa8a878;
        } else if (type === "Fire") {
            return 0xf08030;
        } else if (type === "Fighting") {
            return 0xc03028;
        } else if (type === "Water") {
            return 0x6890f0;
        } else if (type === "Flying") {
            return 0xa890f0;
        } else if (type === "Grass") {
            return 0x78c850;
        } else if (type === "Poison") {
            return 0xa040a0;
        } else if (type === "Electric") {
            return 0xf8d030;
        } else if (type === "Ground") {
            return 0xe0c068;
        } else if (type === "Psychic") {
            return 0xf85888;
        } else if (type === "Rock") {
            return 0xb8a038;
        } else if (type === "Ice") {
            return 0x98d8d8;
        } else if (type === "Bug") {
            return 0xa8b820;
        } else if (type === "Dragon") {
            return 0x7038f8;
        } else if (type === "Ghost") {
            return 0x705898;
        } else if (type === "Dark") {
            return 0x705848;
        } else if (type === "Steel") {
            return 0xb8b8d0;
        } else if (type === "Fairy") {
            return 0xee99ac;
        } else {
            return 0x68a090;
        }
    }

    this.pokemonList = [
        "Bulbasaur",
        "Ivysaur",
        "Venusaur",
        "Charmander",
        "Charmeleon",
        "Charizard",
        "Squirtle",
        "Wartortle",
        "Blastoise",
        "Caterpie",
        "Metapod",
        "Butterfree",
        "Weedle",
        "Kakuna",
        "Beedrill",
        "Pidgey",
        "Pidgeotto",
        "Pidgeot",
        "Rattata",
        "Raticate",
        "Spearow",
        "Fearow",
        "Ekans",
        "Arbok",
        "Pikachu",
        "Raichu",
        "Sandshrew",
        "Sandslash",
        "Nidoran♀",
        "Nidorina",
        "Nidoqueen",
        "Nidoran♂",
        "Nidorino",
        "Nidoking",
        "Clefairy",
        "Clefable",
        "Vulpix",
        "Ninetales",
        "Jigglypuff",
        "Wigglytuff",
        "Zubat",
        "Golbat",
        "Oddish",
        "Gloom",
        "Vileplume",
        "Paras",
        "Parasect",
        "Venonat",
        "Venomoth",
        "Diglett",
        "Dugtrio",
        "Meowth",
        "Persian",
        "Psyduck",
        "Golduck",
        "Mankey",
        "Primeape",
        "Growlithe",
        "Arcanine",
        "Poliwag",
        "Poliwhirl",
        "Poliwrath",
        "Abra",
        "Kadabra",
        "Alakazam",
        "Machop",
        "Machoke",
        "Machamp",
        "Bellsprout",
        "Weepinbell",
        "Victreebel",
        "Tentacool",
        "Tentacruel",
        "Geodude",
        "Graveler",
        "Golem",
        "Ponyta",
        "Rapidash",
        "Slowpoke",
        "Slowbro",
        "Magnemite",
        "Magneton",
        "Farfetch'd",
        "Doduo",
        "Dodrio",
        "Seel",
        "Dewgong",
        "Grimer",
        "Muk",
        "Shellder",
        "Cloyster",
        "Gastly",
        "Haunter",
        "Gengar",
        "Onix",
        "Drowzee",
        "Hypno",
        "Krabby",
        "Kingler",
        "Voltorb",
        "Electrode",
        "Exeggcute",
        "Exeggutor",
        "Cubone",
        "Marowak",
        "Hitmonlee",
        "Hitmonchan",
        "Lickitung",
        "Koffing",
        "Weezing",
        "Rhyhorn",
        "Rhydon",
        "Chansey",
        "Tangela",
        "Kangaskhan",
        "Horsea",
        "Seadra",
        "Goldeen",
        "Seaking",
        "Staryu",
        "Starmie",
        "Mr. Mime",
        "Scyther",
        "Jynx",
        "Electabuzz",
        "Magmar",
        "Pinsir",
        "Tauros",
        "Magikarp",
        "Gyarados",
        "Lapras",
        "Ditto",
        "Eevee",
        "Vaporeon",
        "Jolteon",
        "Flareon",
        "Porygon",
        "Omanyte",
        "Omastar",
        "Kabuto",
        "Kabutops",
        "Aerodactyl",
        "Snorlax",
        "Articuno",
        "Zapdos",
        "Moltres",
        "Dratini",
        "Dragonair",
        "Dragonite",
        "Mewtwo",
        "Mew",
        "Chikorita",
        "Bayleef",
        "Meganium",
        "Cyndaquil",
        "Quilava",
        "Typhlosion",
        "Totodile",
        "Croconaw",
        "Feraligatr",
        "Sentret",
        "Furret",
        "Hoothoot",
        "Noctowl",
        "Ledyba",
        "Ledian",
        "Spinarak",
        "Ariados",
        "Crobat",
        "Chinchou",
        "Lanturn",
        "Pichu",
        "Cleffa",
        "Igglybuff",
        "Togepi",
        "Togetic",
        "Natu",
        "Xatu",
        "Mareep",
        "Flaaffy",
        "Ampharos",
        "Bellossom",
        "Marill",
        "Azumarill",
        "Sudowoodo",
        "Politoed",
        "Hoppip",
        "Skiploom",
        "Jumpluff",
        "Aipom",
        "Sunkern",
        "Sunflora",
        "Yanma",
        "Wooper",
        "Quagsire",
        "Espeon",
        "Umbreon",
        "Murkrow",
        "Slowking",
        "Misdreavus",
        "Unown",
        "Wobbuffet",
        "Girafarig",
        "Pineco",
        "Forretress",
        "Dunsparce",
        "Gligar",
        "Steelix",
        "Snubbull",
        "Granbull",
        "Qwilfish",
        "Scizor",
        "Shuckle",
        "Heracross",
        "Sneasel",
        "Teddiursa",
        "Ursaring",
        "Slugma",
        "Magcargo",
        "Swinub",
        "Piloswine",
        "Corsola",
        "Remoraid",
        "Octillery",
        "Delibird",
        "Mantine",
        "Skarmory",
        "Houndour",
        "Houndoom",
        "Kingdra",
        "Phanpy",
        "Donphan",
        "Porygon2",
        "Stantler",
        "Smeargle",
        "Tyrogue",
        "Hitmontop",
        "Smoochum",
        "Elekid",
        "Magby",
        "Miltank",
        "Blissey",
        "Raikou",
        "Entei",
        "Suicune",
        "Larvitar",
        "Pupitar",
        "Tyranitar",
        "Lugia",
        "Ho-Oh",
        "Celebi",
        "Treecko",
        "Grovyle",
        "Sceptile",
        "Torchic",
        "Combusken",
        "Blaziken",
        "Mudkip",
        "Marshtomp",
        "Swampert",
        "Poochyena",
        "Mightyena",
        "Zigzagoon",
        "Linoone",
        "Wurmple",
        "Silcoon",
        "Beautifly",
        "Cascoon",
        "Dustox",
        "Lotad",
        "Lombre",
        "Ludicolo",
        "Seedot",
        "Nuzleaf",
        "Shiftry",
        "Taillow",
        "Swellow",
        "Wingull",
        "Pelipper",
        "Ralts",
        "Kirlia",
        "Gardevoir",
        "Surskit",
        "Masquerain",
        "Shroomish",
        "Breloom",
        "Slakoth",
        "Vigoroth",
        "Slaking",
        "Nincada",
        "Ninjask",
        "Shedinja",
        "Whismur",
        "Loudred",
        "Exploud",
        "Makuhita",
        "Hariyama",
        "Azurill",
        "Nosepass",
        "Skitty",
        "Delcatty",
        "Sableye",
        "Mawile",
        "Aron",
        "Lairon",
        "Aggron",
        "Meditite",
        "Medicham",
        "Electrike",
        "Manectric",
        "Plusle",
        "Minun",
        "Volbeat",
        "Illumise",
        "Roselia",
        "Gulpin",
        "Swalot",
        "Carvanha",
        "Sharpedo",
        "Wailmer",
        "Wailord",
        "Numel",
        "Camerupt",
        "Torkoal",
        "Spoink",
        "Grumpig",
        "Spinda",
        "Trapinch",
        "Vibrava",
        "Flygon",
        "Cacnea",
        "Cacturne",
        "Swablu",
        "Altaria",
        "Zangoose",
        "Seviper",
        "Lunatone",
        "Solrock",
        "Barboach",
        "Whiscash",
        "Corphish",
        "Crawdaunt",
        "Baltoy",
        "Claydol",
        "Lileep",
        "Cradily",
        "Anorith",
        "Armaldo",
        "Feebas",
        "Milotic",
        "Castform",
        "Kecleon",
        "Shuppet",
        "Banette",
        "Duskull",
        "Dusclops",
        "Tropius",
        "Chimecho",
        "Absol",
        "Wynaut",
        "Snorunt",
        "Glalie",
        "Spheal",
        "Sealeo",
        "Walrein",
        "Clamperl",
        "Huntail",
        "Gorebyss",
        "Relicanth",
        "Luvdisc",
        "Bagon",
        "Shelgon",
        "Salamence",
        "Beldum",
        "Metang",
        "Metagross",
        "Regirock",
        "Regice",
        "Registeel",
        "Latias",
        "Latios",
        "Kyogre",
        "Groudon",
        "Rayquaza",
        "Jirachi",
        "Deoxys",
        "Turtwig",
        "Grotle",
        "Torterra",
        "Chimchar",
        "Monferno",
        "Infernape",
        "Piplup",
        "Prinplup",
        "Empoleon",
        "Starly",
        "Staravia",
        "Staraptor",
        "Bidoof",
        "Bibarel",
        "Kricketot",
        "Kricketune",
        "Shinx",
        "Luxio",
        "Luxray",
        "Budew",
        "Roserade",
        "Cranidos",
        "Rampardos",
        "Shieldon",
        "Bastiodon",
        "Burmy",
        "Wormadam",
        "Mothim",
        "Combee",
        "Vespiquen",
        "Pachirisu",
        "Buizel",
        "Floatzel",
        "Cherubi",
        "Cherrim",
        "Shellos",
        "Gastrodon",
        "Ambipom",
        "Drifloon",
        "Drifblim",
        "Buneary",
        "Lopunny",
        "Mismagius",
        "Honchkrow",
        "Glameow",
        "Purugly",
        "Chingling",
        "Stunky",
        "Skuntank",
        "Bronzor",
        "Bronzong",
        "Bonsly",
        "Mime Jr.",
        "Happiny",
        "Chatot",
        "Spiritomb",
        "Gible",
        "Gabite",
        "Garchomp",
        "Munchlax",
        "Riolu",
        "Lucario",
        "Hippopotas",
        "Hippowdon",
        "Skorupi",
        "Drapion",
        "Croagunk",
        "Toxicroak",
        "Carnivine",
        "Finneon",
        "Lumineon",
        "Mantyke",
        "Snover",
        "Abomasnow",
        "Weavile",
        "Magnezone",
        "Lickilicky",
        "Rhyperior",
        "Tangrowth",
        "Electivire",
        "Magmortar",
        "Togekiss",
        "Yanmega",
        "Leafeon",
        "Glaceon",
        "Gliscor",
        "Mamoswine",
        "Porygon-Z",
        "Gallade",
        "Probopass",
        "Dusknoir",
        "Froslass",
        "Rotom",
        "Uxie",
        "Mesprit",
        "Azelf",
        "Dialga",
        "Palkia",
        "Heatran",
        "Regigigas",
        "Giratina",
        "Cresselia",
        "Phione",
        "Manaphy",
        "Darkrai",
        "Shaymin",
        "Arceus",
        "Victini",
        "Snivy",
        "Servine",
        "Serperior",
        "Tepig",
        "Pignite",
        "Emboar",
        "Oshawott",
        "Dewott",
        "Samurott",
        "Patrat",
        "Watchog",
        "Lillipup",
        "Herdier",
        "Stoutland",
        "Purrloin",
        "Liepard",
        "Pansage",
        "Simisage",
        "Pansear",
        "Simisear",
        "Panpour",
        "Simipour",
        "Munna",
        "Musharna",
        "Pidove",
        "Tranquill",
        "Unfezant",
        "Blitzle",
        "Zebstrika",
        "Roggenrola",
        "Boldore",
        "Gigalith",
        "Woobat",
        "Swoobat",
        "Drilbur",
        "Excadrill",
        "Audino",
        "Timburr",
        "Gurdurr",
        "Conkeldurr",
        "Tympole",
        "Palpitoad",
        "Seismitoad",
        "Throh",
        "Sawk",
        "Sewaddle",
        "Swadloon",
        "Leavanny",
        "Venipede",
        "Whirlipede",
        "Scolipede",
        "Cottonee",
        "Whimsicott",
        "Petilil",
        "Lilligant",
        "Basculin",
        "Sandile",
        "Krokorok",
        "Krookodile",
        "Darumaka",
        "Darmanitan",
        "Maractus",
        "Dwebble",
        "Crustle",
        "Scraggy",
        "Scrafty",
        "Sigilyph",
        "Yamask",
        "Cofagrigus",
        "Tirtouga",
        "Carracosta",
        "Archen",
        "Archeops",
        "Trubbish",
        "Garbodor",
        "Zorua",
        "Zoroark",
        "Minccino",
        "Cinccino",
        "Gothita",
        "Gothorita",
        "Gothitelle",
        "Solosis",
        "Duosion",
        "Reuniclus",
        "Ducklett",
        "Swanna",
        "Vanillite",
        "Vanillish",
        "Vanilluxe",
        "Deerling",
        "Sawsbuck",
        "Emolga",
        "Karrablast",
        "Escavalier",
        "Foongus",
        "Amoonguss",
        "Frillish",
        "Jellicent",
        "Alomomola",
        "Joltik",
        "Galvantula",
        "Ferroseed",
        "Ferrothorn",
        "Klink",
        "Klang",
        "Klinklang",
        "Tynamo",
        "Eelektrik",
        "Eelektross",
        "Elgyem",
        "Beheeyem",
        "Litwick",
        "Lampent",
        "Chandelure",
        "Axew",
        "Fraxure",
        "Haxorus",
        "Cubchoo",
        "Beartic",
        "Cryogonal",
        "Shelmet",
        "Accelgor",
        "Stunfisk",
        "Mienfoo",
        "Mienshao",
        "Druddigon",
        "Golett",
        "Golurk",
        "Pawniard",
        "Bisharp",
        "Bouffalant",
        "Rufflet",
        "Braviary",
        "Vullaby",
        "Mandibuzz",
        "Heatmor",
        "Durant",
        "Deino",
        "Zweilous",
        "Hydreigon",
        "Larvesta",
        "Volcarona",
        "Cobalion",
        "Terrakion",
        "Virizion",
        "Tornadus",
        "Thundurus",
        "Reshiram",
        "Zekrom",
        "Landorus",
        "Kyurem",
        "Keldeo",
        "Meloetta",
        "Genesect",
        "Chespin",
        "Quilladin",
        "Chesnaught",
        "Fennekin",
        "Braixen",
        "Delphox",
        "Froakie",
        "Frogadier",
        "Greninja",
        "Bunnelby",
        "Diggersby",
        "Fletchling",
        "Fletchinder",
        "Talonflame",
        "Scatterbug",
        "Spewpa",
        "Vivillon",
        "Litleo",
        "Pyroar",
        "Flabébé",
        "Floette",
        "Florges",
        "Skiddo",
        "Gogoat",
        "Pancham",
        "Pangoro",
        "Furfrou",
        "Espurr",
        "Meowstic",
        "Honedge",
        "Doublade",
        "Aegislash",
        "Spritzee",
        "Aromatisse",
        "Swirlix",
        "Slurpuff",
        "Inkay",
        "Malamar",
        "Binacle",
        "Barbaracle",
        "Skrelp",
        "Dragalge",
        "Clauncher",
        "Clawitzer",
        "Helioptile",
        "Heliolisk",
        "Tyrunt",
        "Tyrantrum",
        "Amaura",
        "Aurorus",
        "Sylveon",
        "Hawlucha",
        "Dedenne",
        "Carbink",
        "Goomy",
        "Sliggoo",
        "Goodra",
        "Klefki",
        "Phantump",
        "Trevenant",
        "Pumpkaboo",
        "Gourgeist",
        "Bergmite",
        "Avalugg",
        "Noibat",
        "Noivern",
        "Xerneas",
        "Yveltal",
        "Zygarde",
        "Diancie",
        "Hoopa",
        "Volcanion",
        "Rowlet",
        "Dartrix",
        "Decidueye",
        "Litten",
        "Torracat",
        "Incineroar",
        "Popplio",
        "Brionne",
        "Primarina",
        "Pikipek",
        "Trumbeak",
        "Toucannon",
        "Yungoos",
        "Gumshoos",
        "Grubbin",
        "Charjabug",
        "Vikavolt",
        "Crabrawler",
        "Crabominable",
        "Oricorio",
        "Cutiefly",
        "Ribombee",
        "Rockruff",
        "Lycanroc",
        "Wishiwashi",
        "Mareanie",
        "Toxapex",
        "Mudbray",
        "Mudsdale",
        "Dewpider",
        "Araquanid",
        "Fomantis",
        "Lurantis",
        "Morelull",
        "Shiinotic",
        "Salandit",
        "Salazzle",
        "Stufful",
        "Bewear",
        "Bounsweet",
        "Steenee",
        "Tsareena",
        "Comfey",
        "Oranguru",
        "Passimian",
        "Wimpod",
        "Golisopod",
        "Sandygast",
        "Palossand",
        "Pyukumuku",
        "Type: Null",
        "Silvally",
        "Minior",
        "Komala",
        "Turtonator",
        "Togedemaru",
        "Mimikyu",
        "Bruxish",
        "Drampa",
        "Dhelmise",
        "Jangmo-o",
        "Hakamo-o",
        "Kommo-o",
        "Tapu Koko",
        "Tapu Lele",
        "Tapu Bulu",
        "Tapu Fini",
        "Cosmog",
        "Cosmoem",
        "Solgaleo",
        "Lunala",
        "Nihilego",
        "Buzzwole",
        "Pheromosa",
        "Xurkitree",
        "Celesteela",
        "Kartana",
        "Guzzlord",
        "Necrozma",
        "Magearna",
        "Marshadow",
        "Poipole",
        "Naganadel",
        "Stakataka",
        "Blacephalon",
        "Zeraora",
        "Meltan",
        "Melmetal",
        "Grookey",
        "Thwackey",
        "Rillaboom",
        "Scorbunny",
        "Raboot",
        "Cinderace",
        "Sobble",
        "Drizzile",
        "Inteleon",
        "Skwovet",
        "Greedent",
        "Rookidee",
        "Corvisquire",
        "Corviknight",
        "Blipbug",
        "Dottler",
        "Orbeetle",
        "Nickit",
        "Thievul",
        "Gossifleur",
        "Eldegoss",
        "Wooloo",
        "Dubwool",
        "Chewtle",
        "Drednaw",
        "Yamper",
        "Boltund",
        "Rolycoly",
        "Carkol",
        "Coalossal",
        "Applin",
        "Flapple",
        "Appletun",
        "Silicobra",
        "Sandaconda",
        "Cramorant",
        "Arrokuda",
        "Barraskewda",
        "Toxel",
        "Toxtricity",
        "Sizzlipede",
        "Centiskorch",
        "Clobbopus",
        "Grapploct",
        "Sinistea",
        "Polteageist",
        "Hatenna",
        "Hattrem",
        "Hatterene",
        "Impidimp",
        "Morgrem",
        "Grimmsnarl",
        "Obstagoon",
        "Perrserker",
        "Cursola",
        "Sirfetch'd",
        "Mr. Rime",
        "Runerigus",
        "Milcery",
        "Alcremie",
        "Falinks",
        "Pincurchin",
        "Snom",
        "Frosmoth",
        "Stonjourner",
        "Eiscue",
        "Indeedee",
        "Morpeko",
        "Cufant",
        "Copperajah",
        "Dracozolt",
        "Arctozolt",
        "Dracovish",
        "Arctovish",
        "Duraludon",
        "Dreepy",
        "Drakloak",
        "Dragapult",
        "Zacian",
        "Zamazenta",
        "Eternatus",
        "Kubfu",
        "Urshifu",
        "Zarude",
        "Regieleki",
        "Regidrago",
        "Glastrier",
        "Spectrier",
        "Calyrex",
        "Wyrdeer",
        "Kleavor",
        "Ursaluna",
        "Basculegion",
        "Sneasler",
        "Overqwil",
        "Enamorus",
        "Sprigatito",
        "Floragato",
        "Meowscarada",
        "Fuecoco",
        "Crocalor",
        "Skeledirge",
        "Quaxly",
        "Quaxwell",
        "Quaquaval",
        "Lechonk",
        "Oinkologne",
        "Tarountula",
        "Spidops",
        "Nymble",
        "Lokix",
        "Pawmi",
        "Pawmo",
        "Pawmot",
        "Tandemaus",
        "Maushold",
        "Fidough",
        "Dachsbun",
        "Smoliv",
        "Dolliv",
        "Arboliva",
        "Squawkabilly",
        "Nacli",
        "Naclstack",
        "Garganacl",
        "Charcadet",
        "Armarouge",
        "Ceruledge",
        "Tadbulb",
        "Bellibolt",
        "Wattrel",
        "Kilowattrel",
        "Maschiff",
        "Mabosstiff",
        "Shroodle",
        "Grafaiai",
        "Bramblin",
        "Brambleghast",
        "Toedscool",
        "Toedscruel",
        "Klawf",
        "Capsakid",
        "Scovillain",
        "Rellor",
        "Rabsca",
        "Flittle",
        "Espathra",
        "Tinkatink",
        "Tinkatuff",
        "Tinkaton",
        "Wiglett",
        "Wugtrio",
        "Bombirdier",
        "Finizen",
        "Palafin",
        "Varoom",
        "Revavroom",
        "Cyclizar",
        "Orthworm",
        "Glimmet",
        "Glimmora",
        "Greavard",
        "Houndstone",
        "Flamigo",
        "Cetoddle",
        "Cetitan",
        "Veluza",
        "Dondozo",
        "Tatsugiri",
        "Annihilape",
        "Clodsire",
        "Farigiraf",
        "Dudunsparce",
        "Kingambit",
        "Great Tusk",
        "Scream Tail",
        "Brute Bonnet",
        "Flutter Mane",
        "Slither Wing",
        "Sandy Shocks",
        "Iron Treads",
        "Iron Bundle",
        "Iron Hands",
        "Iron Jugulis",
        "Iron Moth",
        "Iron Thorns",
        "Frigibax",
        "Arctibax",
        "Baxcalibur",
        "Gimmighoul",
        "Gholdengo",
        "Wo-Chien",
        "Chien-Pao",
        "Ting-Lu",
        "Chi-Yu",
        "Roaring Moon",
        "Iron Valiant",
        "Koraidon",
        "Miraidon",
        "Walking Wake",
        "Iron Leaves",
        "Dipplin",
        "Poltchageist",
        "Sinistcha",
        "Okidogi",
        "Munkidori",
        "Fezandipiti",
        "Ogerpon",
        "Archaludon",
        "Hydrapple",
        "Gouging Fire",
        "Raging Bolt",
        "Iron Boulder",
        "Iron Crown",
        "Terapagos",
        "Pecharunt"
    ]
}